import { Resend } from 'resend';
import { NextRequest, NextResponse } from 'next/server';
import { auth, currentUser } from '@clerk/nextjs/server';

const resend = new Resend(process.env.RESEND_API_KEY);

export async function POST(req: NextRequest) {
    try {
        const { userId } = await auth();
        const user = await currentUser();

        if (!userId || !user) {
            return new NextResponse("Unauthorized", { status: 401 });
        }

        const { proposal, recipientEmail } = await req.json();

        if (!proposal) {
            return new NextResponse("Proposal content is required", { status: 400 });
        }

        // If no recipient provided, send to self
        const emailToSend = recipientEmail || user.emailAddresses[0]?.emailAddress;

        if (!emailToSend) {
            return new NextResponse("No email found", { status: 400 });
        }

        const { data, error } = await resend.emails.send({
            from: 'ProposalAI <onboarding@resend.dev>', // Use default until domain verified
            to: [emailToSend],
            subject: 'Your AI Generated Proposal',
            html: `
        <h1>Here is your generated proposal</h1>
        <div style="white-space: pre-wrap; font-family: sans-serif; padding: 20px; border: 1px solid #eaeaea; border-radius: 5px;">
          ${proposal.replace(/\n/g, '<br/>')}
        </div>
        <p>Generated by ProposalAI</p>
      `,
        });

        if (error) {
            console.error(error);
            return NextResponse.json({ error }, { status: 500 });
        }

        return NextResponse.json(data);

    } catch (error) {
        console.error(error);
        return NextResponse.json({ error: 'Internal Server Error' }, { status: 500 });
    }
}
